services:
  maptoposter:
    image: ghcr.io/alivebe-a11y/3dmap:latest
    container_name: maptoposter
    ports:
      - "5025:5025"
    volumes:
      - ./posters:/app/posters
      - ./cache:/app/cache
      - ./badges:/app/badges
      - ./stadium_data.py:/app/stadium_data.py
    environment:
      - MAPBOX_TOKEN=${MAPBOX_TOKEN}
    restart: unless-stopped

networks: {}
